import Vue from "vue";
import axios from "axios";
import lodash from "lodash";
import moment from "moment";

Vue.prototype.$axios = axios;
Vue.prototype._ = lodash;
Vue.prototype.moment = moment;



// /* v1.1.3+ registration methods */
// Vue.use(Base);
// Vue.use(Affix);
// Vue.use(Anchor);
// Vue.use(AutoComplete);
// Vue.use(Alert);
// Vue.use(Avatar);
// Vue.use(BackTop);
// Vue.use(Badge);
// Vue.use(Breadcrumb);
// Vue.use(Button);
// Vue.use(Calendar);
// Vue.use(Card);
// Vue.use(Collapse);
// Vue.use(Carousel);
// Vue.use(Cascader);
// Vue.use(Checkbox);
// Vue.use(Col);
// Vue.use(DatePicker);
// Vue.use(Divider);
// Vue.use(Drawer);
// Vue.use(Dropdown);
// Vue.use(Form);
// Vue.use(FormModel);
// Vue.use(Icon);
// Vue.use(Input);
// Vue.use(InputNumber);
// Vue.use(Layout);
// Vue.use(List);
// Vue.use(LocaleProvider);
// Vue.use(Menu);
// Vue.use(Mentions);
// Vue.use(Modal);
// Vue.use(Pagination);
// Vue.use(Popconfirm);
// Vue.use(Popover);
// Vue.use(Progress);
// Vue.use(Radio);
// Vue.use(Rate);
// Vue.use(Row);
// Vue.use(Select);
// Vue.use(Slider);
// Vue.use(Spin);
// Vue.use(Statistic);
// Vue.use(Steps);
// Vue.use(Switch);
// Vue.use(Transfer);
// Vue.use(Tree);
// Vue.use(TreeSelect);
// Vue.use(Tabs);
// Vue.use(Tag);
// Vue.use(TimePicker);
// Vue.use(Timeline);
// Vue.use(Tooltip);
// Vue.use(Upload);
// Vue.use(Skeleton);
// Vue.use(Comment);
// Vue.use(ConfigProvider);
// Vue.use(Empty);
// Vue.use(Result);
// Vue.use(Descriptions);
// Vue.use(PageHeader);
// Vue.use(Space);
